name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'

      - name: Get dependencies
        run: go mod download

      - name: Build binaries
        run: |
          mkdir -p build
          
          # Linux
          GOOS=linux GOARCH=amd64 go build -ldflags="-s -w" -o build/cellular_logger-linux-amd64 main.go
          GOOS=linux GOARCH=arm64 go build -ldflags="-s -w" -o build/cellular_logger-linux-arm64 main.go
          GOOS=linux GOARCH=arm go build -ldflags="-s -w" -o build/cellular_logger-linux-arm main.go
          
          # macOS
          GOOS=darwin GOARCH=amd64 go build -ldflags="-s -w" -o build/cellular_logger-darwin-amd64 main.go
          GOOS=darwin GOARCH=arm64 go build -ldflags="-s -w" -o build/cellular_logger-darwin-arm64 main.go
          
          # Windows
          GOOS=windows GOARCH=amd64 go build -ldflags="-s -w" -o build/cellular_logger-windows-amd64.exe main.go
          GOOS=windows GOARCH=arm64 go build -ldflags="-s -w" -o build/cellular_logger-windows-arm64.exe main.go

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            build/cellular_logger-linux-amd64
            build/cellular_logger-linux-arm64
            build/cellular_logger-linux-arm
            build/cellular_logger-darwin-amd64
            build/cellular_logger-darwin-arm64
            build/cellular_logger-windows-amd64.exe
            build/cellular_logger-windows-arm64.exe
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}